const Sequelize = require('sequelize');

//const path = 'mysql://root:@localhost:3306/sequelize_demo';//
//const sequelize = new Sequelize(path);

const sequelize = new Sequelize('sequelize_demo', 'root', null, {
  host: 'localhost',
  dialect: 'mysql'
});



sequelize.authenticate().then(() => {
  console.log('Connect to MySQL successfully.');
}).catch(err => {
  console.error('Unable to connect to the database:', err);
}).finally(() => {
  //sequelize.close();
});


const User = sequelize.define('user', {
    // attributes
    firstName: {
        type: Sequelize.STRING,
        allowNull: false
    },
    lastName: {
        type: Sequelize.STRING
        // allowNull defaults to true
    }
}, {
        // options
    });

User.sync({ force: false }).then(() => {
    // Now the `users` table in the database corresponds to the model definition
    return User.create({
        firstName: 'John',
        lastName: 'Hancock'
    });
});

// Find all users
User.findAll().then(users => {
    console.log("All users:", JSON.stringify(users, null, 4));
});

// Create a new user
User.create({ firstName: "Jane", lastName: "Doe" }).then(jane => {
    console.log("Jane's auto-generated ID:", jane.id);
});

// Delete everyone named "Jane"
User.destroy({
    where: {
        firstName: "Jane"
    }
}).then(() => {
    console.log("Done");
});

// Change everyone without a last name to "Doe"
User.update({ lastName: "Doe" }, {
    where: {
        lastName: null
    }
}).then(() => {
    console.log("Done");
});

const express = require('express');
const app = express();
const swaggerUi = require('swagger-ui-express');
//const swaggerDocument = require('./swagger.json');

const swaggerJsdoc = require('swagger-jsdoc');


const options = {
  swaggerDefinition: {
    // Like the one described here: https://swagger.io/specification/#infoObject
    info: {
      title: 'Test API',
      version: '1.0.0',
      description: 'Test Express API with autogenerated swagger doc',
    },
  },
  // List of files to be processes. You can also set globs './routes/*.js'
  apis: ['endpoints.js'],
};



const specs = swaggerJsdoc(options);
app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(specs));

//app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerDocument));



app.get('/', function (req, res) {
   res.send('Hello World');
})

app.get('/getallusers', function (req, res) {
    res.send('All users');
})

var server = app.listen(8081, function () {
   var host = server.address().address
   var port = server.address().port
   
   console.log("Example app listening at http://%s:%s", host, port)
})





